export const employees = [
  {
    FirstName: "Tony",
    LastName: "Stark",
    StartDate: "12/08/1993",
    Department: "Sales",
    DateOfBirth: "15/02/1978",
    Street: "13 rue de Paris",
    City: "Paris",
    State: "AL",
    ZipCode: "75005",
  },
  {
    FirstName: "Steve",
    LastName: "Job",
    StartDate: "10/04/1997",
    Department: "Marketing",
    DateOfBirth: "11/09/1967",
    Street: "13 rue victor Hugo",
    City: "Lyon",
    State: "AS",
    ZipCode: "005",
  },
  {
    FirstName: "Jeff",
    LastName: "Bezos",
    StartDate: "10/12/2011",
    Department: "Engeenering",
    DateOfBirth: "23/05/1969",
    Street: "150 avenue Montpassant",
    City: "Bordeaux",
    State: "CO",
    ZipCode: "33120",
  },
  {
    FirstName: "Elon",
    LastName: "Musk",
    StartDate: "21/01/2008",
    Department: "Engeenering",
    DateOfBirth: "01/02/1976",
    Street: "38 rue Victor Hugo",
    City: "Toulouse",
    State: "DC",
    ZipCode: "32000",
  },
  {
    FirstName: "Bill",
    LastName: "Gates",
    StartDate: "24/12/1996",
    Department: "Human Ressources",
    DateOfBirth: "04/09/1968",
    Street: "45 rue de Chateaubriand",
    City: "Puys en Velay",
    State: "GU",
    ZipCode: "47000",
  },
  {
    FirstName: "Tony",
    LastName: "Stark",
    StartDate: "12/08/1993",
    Department: "Sales",
    DateOfBirth: "15/02/1978",
    Street: "13 rue de Paris",
    City: "Paris",
    State: "AL",
    ZipCode: "75005",
  },
  {
    FirstName: "Steve",
    LastName: "Job",
    StartDate: "10/04/1997",
    Department: "Marketing",
    DateOfBirth: "11/09/1967",
    Street: "13 rue victor Hugo",
    City: "Lyon",
    State: "AS",
    ZipCode: "005",
  },
  {
    FirstName: "Jeff",
    LastName: "Bezos",
    StartDate: "10/12/2011",
    Department: "Engeenering",
    DateOfBirth: "23/05/1969",
    Street: "150 avenue Montpassant",
    City: "Bordeaux",
    State: "CO",
    ZipCode: "33120",
  },
  {
    FirstName: "Elon",
    LastName: "Musk",
    StartDate: "21/01/2008",
    Department: "Engeenering",
    DateOfBirth: "01/02/1976",
    Street: "38 rue Victor Hugo",
    City: "Toulouse",
    State: "DC",
    ZipCode: "32000",
  },
  {
    FirstName: "Bill",
    LastName: "Gates",
    StartDate: "24/12/1996",
    Department: "Human Ressources",
    DateOfBirth: "04/09/1968",
    Street: "45 rue de Chateaubriand",
    City: "Puys en Velay",
    State: "GU",
    ZipCode: "47000",
  },
  {
    FirstName: "Tony",
    LastName: "Stark",
    StartDate: "12/08/1993",
    Department: "Sales",
    DateOfBirth: "15/02/1978",
    Street: "13 rue de Paris",
    City: "Paris",
    State: "AL",
    ZipCode: "75005",
  },
  {
    FirstName: "Steve",
    LastName: "Job",
    StartDate: "10/04/1997",
    Department: "Marketing",
    DateOfBirth: "11/09/1967",
    Street: "13 rue victor Hugo",
    City: "Lyon",
    State: "AS",
    ZipCode: "005",
  },
  {
    FirstName: "Jeff",
    LastName: "Bezos",
    StartDate: "10/12/2011",
    Department: "Engeenering",
    DateOfBirth: "23/05/1969",
    Street: "150 avenue Montpassant",
    City: "Bordeaux",
    State: "CO",
    ZipCode: "33120",
  },
  {
    FirstName: "Elon",
    LastName: "Musk",
    StartDate: "21/01/2008",
    Department: "Engeenering",
    DateOfBirth: "01/02/1976",
    Street: "38 rue Victor Hugo",
    City: "Toulouse",
    State: "DC",
    ZipCode: "32000",
  },
  {
    FirstName: "Bill",
    LastName: "Gates",
    StartDate: "24/12/1996",
    Department: "Human Ressources",
    DateOfBirth: "04/09/1968",
    Street: "45 rue de Chateaubriand",
    City: "Puys en Velay",
    State: "GU",
    ZipCode: "47000",
  },
];
